### ISSUE TITLE
[Alpha branch] Project does not compile on Mac OS Unity 2017.3

### ISSUE THREAD

**Issue by Zammy** [sebas77/Svelto.ECS.Examples.Survival#4]
I might be doing something wrong but there is no explanation how to setup project.
I am doing:
```
     git checkout alpha
     git submodule init
     git submodule update
```

I get many compile errors.

```
Assets/Svelto-ECS/ECS/EntityDescriptor.cs(39,29): error CS0121: The call is ambiguous between the following methods or properties: `FastConcatUtility.FastConcat<string>(this string, string)' and `FastConcatUtility.FastConcat<string>(this string, string)'

Assets/Svelto-ECS-Example/Scripts/ECS/Engines/EnemyEngines/EnemyAttackEngine.cs(67,47): error CS1502: The best overloaded method match for Svelto.ECS.Sequencer.Next<Svelto.ECS.Example.Survive.Components.Damageable.TargetDamageInfo>(Svelto.ECS.IEngine, ref Svelto.ECS.Example.Survive.Components.Damageable.TargetDamageInfo)' has some invalid arguments

Assets/Svelto-ECS-Example/Scripts/ECS/Engines/OtherEngines/HealthEngine.cs(53,76): error CS1503: Argument `#2' cannot convert `Svelto.ECS.IRemoveEntityComponent [Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -- /Users/evgenipetrov/Work/Svelto.ECS.Example/Assets/Svelto-ECS/ECS/IRemoveEntityComponent.cs]' expression to type `Svelto.ECS.IRemoveEntityComponent [Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -- /Users/evgenipetrov/Work/Svelto.ECS.Example/Library/ScriptAssemblies/Assembly-CSharp-firstpass.dll]'
```

and so on... 

What am I doing wrong?

**Comment by Zammy** [comment]
I got the repo again and this time I have no issue with compilation. You can close this one.
